### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by vmwxiong** [nick-lvov-dev/typescript-explicit-types#11]
Get this error when I try to use it:
```
Command 'Generate explicit type' resulted in an error (Cannot read properties of undefined (reading '0'))
```

**Comment by christopher-kapic** [comment]
I have the same question. Would be _awesome_ if it still did, but it doesn't show the thing in the menu for me (I'm on MacOS).

**Comment by nick-lvov-dev** [comment]
Sorry guys, I switched to WebStorm so this extension is abandoned at this point. You're free to fork it though
